version: "{branch}-{build}"
skip_branch_with_pr: true
skip_commits:
  files:
    - docs/*
image:
  - Visual Studio 2022
  - Ubuntu2004
configuration: Release
platform: x64
init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
          Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME-$env:APPVEYOR_BUILD_NUMBER"
      }
      else
      {
          Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_COMMIT.Substring(0, 7))-$env:APPVEYOR_BUILD_NUMBER"
      }
for:
  - matrix:
      only:
        - image: Visual Studio 2022

    environment:
      Qt6_DIR: C:\Qt\6.4.0\msvc2019_64

    install:
      - git submodule update --init --recursive

    build_script:
      - cmd: cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -S%APPVEYOR_BUILD_FOLDER% -B%APPVEYOR_BUILD_FOLDER%/build -G "Visual Studio 17 2022" -T host=x64 -A x64
      - cmd: cmake --build %APPVEYOR_BUILD_FOLDER%/build --config Release --
  - matrix:
      only:
        - image: Ubuntu2004

    environment:
      Qt6_DIR: $HOME/Qt/6.4.0/gcc_64

    install:
      - git submodule update --init --recursive
      - sudo apt-get -y install gcc-11 g++-11

    build_script:
      - ps: cmake --no-warn-unused-cli -DCMAKE_PREFIX_PATH="$HOME/Qt/6.4.0/gcc_64/lib/cmake" -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -S./ -B./build -G "Unix Makefiles"
      - ps: cmake --build ./build --config Release --
