version: '{branch}-{build}'
branches:
  only:
  - master
skip_non_tags: true
image: Visual Studio 2019
configuration: Release
platform: x64
init:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")

    {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME-$env:APPVEYOR_BUILD_NUMBER"
    }

    else

    {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_COMMIT.Substring(0, 7))-$env:APPVEYOR_BUILD_NUMBER"
    }
environment:
  QTDIR: C:\Qt\5.12.5\msvc2017_64
  OPENSSL: C:\OpenSSL-v111-Win64\bin
  QTIFW: C:\Qt\Tools\QtInstallerFramework\3.1\bin
build_script:
  - cmd: msbuild "C:\projects\quasar\Quasar.sln" /m /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:QtInstall=%QTDIR%
after_build:
- ps: .\deploy\wincreateinstall.ps1 -portable -name "$($env:APPVEYOR_BUILD_VERSION)"
